import { Supervisor, WipLookupItem } from './types';

export const SHELF_LIFE_DAYS = 90;

export const SUPERVISORS = [
  Supervisor.QUMARS,
  Supervisor.VIMAL,
  Supervisor.RAMZAN,
  Supervisor.NEERAJ,
];

// Database populated from "ALL WIP CODES.xlsb"
export const MOCK_WIP_DATABASE: WipLookupItem[] = [
  { code: 'WIP029AN', name: 'CHICKEN MAYO MIX' },
  { code: 'WIP377AN', name: 'PESTO CHICKEN MIX TWELVE' },
  { code: 'WIP112AN', name: 'COLESLAW MIX' },
  { code: 'WIP031AN', name: 'TUNA & SWEETCORN MIX' },
  { code: 'WIP337AN', name: 'TUNA MAYO CUCUMBER' },
  { code: 'WIP032AN', name: 'TUNA MAYO MIX' },
  { code: 'WIP115AN', name: 'CHICKEN MAYO SWEETCORN' },
  { code: 'WIP114AN', name: 'DOUBLE CHEESE AND SPRING ONION MIX' },
  { code: 'WIP027AN', name: 'EGG MAYO MIX' },
  { code: 'WIP019AN', name: 'DIJON MUSTARD MAYO MIX' },
  { code: 'WIP109AN', name: 'CORONATION CHICKPEA MIX' },
  { code: 'WIP051AR', name: 'CORONATION CHICKEN MIX' },
  { code: 'WIP281AN', name: 'BLACK BEAN AVOCADO SWEETCORN MIX' },
  { code: 'WIP340AN', name: 'MAYO AND CHOPPED BACON' },
  { code: 'WIP376AN', name: 'TUNA MAYO, HORSERADISH, ONION' },
  { code: 'WIP084AN', name: 'TUNA MAYO & HORSERADISH MIX' },
  { code: 'WIP005AN', name: 'PRAWN MAYONNAISE MIX' },
  { code: 'WIP067AN', name: 'CHICKEN CAESAR MIX' },
  { code: 'WIP072AN', name: 'LEMON PEPPER MAYO MIX' },
  { code: 'WIP381AN', name: 'CREAM CHEESE & DICED CUCUMBER' },
  { code: 'WIP307AN', name: 'NDUJA PASTE' },
  { code: 'WIP297AN', name: 'EGG MUSTARD MAYO MIX' },
  { code: 'WIP302AN', name: 'SOMKED MACKEREL PATE MIX' },
  { code: 'WIP284AN', name: 'SHREDDED CHICKEN BIRRIA MIX' },
  { code: 'WIP288AN', name: 'CRANBERRY MIX' },
  { code: 'WIP332AN', name: 'CREAM CHEESE, DILL, CHIVES AND CAPERS MIX' },
  { code: 'WIP338AN', name: 'WHITE CABBAGE COLESLAW MIX' },
  { code: 'WIP335AN', name: 'DOUBE CHEESE & TOMATO' },
  { code: 'WIP074AN', name: 'CHICKEN & BACON MAYO MIX' },
  { code: 'WIP266AN', name: 'PULLED CHICKEN MAYO MIX' },
  { code: 'WIP227AN', name: 'CRISPY ONION MAYO MIX' },
  { code: 'WIP310AN', name: 'SAGE ONION AND BUTTER STUFFING' },
  { code: 'WIP006AN', name: 'HOISIN DUCK MIX' },
  { code: 'WIP379AN', name: 'CHICKEN NDUJA LEMON MAYO MIX' },
  { code: 'DABLKS002', name: 'GRILLED VEGETABLE COUS COUS SALAD' },
  { code: 'WIP378AN', name: 'CHICKEN CAESAR WRAP MIX' },
  { code: 'WIP380AN', name: 'CHICKEN CAESAR 12.5% CHEESE' },
  { code: 'WIP062AN', name: 'SWEET CHILLI CHICKEN MIX' },
  { code: 'WIP157AN', name: 'CHIPOTLE CHICKEN BURRITO MIX' },
  { code: 'WIP419AN', name: 'LIME MARINATED RED ONIONS MIX' },
  { code: 'WIP277AN', name: 'CHICKPEA SALAD MIX' },
  { code: 'WIP276AN', name: 'CARROT & CABBAGE PICKLE' },
  { code: 'WIP286AN', name: 'BULGUR WHEAT AND CHICKPEA HARISSA MIX' },
  { code: 'WIP073AN', name: 'TABBOULEH STYLE MIX' },
  { code: 'WIP117AN', name: 'FIRE ROASTED PASTA SALAD MIX' },
  { code: 'WIP298AN', name: 'VEGAN CORONATION GREEN CHICKPEA MIX' },
  { code: 'WIP372AN', name: 'INDIAN SNACK SALAD MIX AVANTI' },
  { code: 'WIP290AN', name: 'SEASONED CREAM CHEESE' },
  { code: 'WIP287AN', name: 'CORONATION EGG MAYO MIX' },
  { code: 'WIP283AN', name: 'BIRRIA SWEET POTATO MIX' },
  { code: 'WIP226AN', name: 'NOVATION STARCH SEAL MIX (GLOOP)' },
  { code: 'WIP282AN', name: 'CHIPOTLE LIME MAYO MIX' },
  { code: 'WIP278AN', name: 'VEGAN CORIANDER MAYO' },
  { code: 'WIP063AN', name: 'ROAST TOMATO HOUMOUS' },
  { code: 'WIP034AN', name: 'SCRAMBLED EGG MIX' },
  { code: 'WIP280AN', name: 'REFRIED BEANS AND JALAPENOS MIX (STARCH REMOVED)' },
  { code: 'WIP008AN', name: 'VEGAN SLAW MIX' },
  { code: 'WIP187AN', name: 'FREE RANGE EGG MAYO' },
  { code: 'WIP336AN', name: 'RAINBOW SLAW MIX' },
  { code: 'WIP308AN', name: 'MUSTARD AND HARD CHEESE MIX' },
  { code: 'WIP275AN', name: 'NDUJA MAYO MIX' },
  { code: 'WIP046AN', name: 'STUFFING AND WATER MIX' },
  { code: 'WIP185AN', name: 'VEGAN MAC AND NO CHEESE' },
  { code: 'WIP004AN', name: 'VEGAN GHERKIN DIJON MUSTARD MAYO' },
  { code: 'WIP048AN', name: 'PULLED CHICKEN MAYONNAISE' },
  { code: 'WIP362AN', name: 'DOUBLE CHEESE ROAST TOMATOES CHUTNEY TWELVE' },
  { code: 'WIP291AN', name: 'SEASONED EGG MAYO & CHIVES' },
  { code: 'WIP290AN', name: 'SEASONAL SOFT CREAM TWELVE' },
  { code: 'WIP315AN', name: 'CREAM CHEESE, DILL, CHIVES & CAPERS MIX' },
  { code: 'WIP054AN', name: 'CREAM CHEESE MIX' },
  { code: 'WIP052AN', name: 'MIXED CHEESE & ROAST TOMATO MIX' },
  { code: 'WIP289AN', name: 'PICKLED CUCUMBER MIX -- CDM' },
  { code: 'WIP050AN', name: 'EGG MAYO & CHIVES' },
  { code: 'WIP309AN', name: 'KIMCHI CHEESE MIX' },
  { code: 'WIP351AN', name: 'FETA AND TOMATO MIX' },
  { code: 'WIP349AN', name: 'BBQ CHICKEN MIX' },
  { code: 'WIP352AN', name: 'ROASTED VEGETABLES AND MOZZARELLA MIX' },
  { code: 'WIP365AN', name: 'SLOW ROASTED TOMATO MIX' },
  { code: 'WIP036AN', name: 'WHOLEGRAIN MUSTARD MAYONNAISE' },
  { code: 'WIP369AN', name: 'SHKSHUKA MUSRHOOM MIX' },
  { code: 'WIP019AN', name: 'DIJON MUSTARD MAYO MIX' },
  { code: 'WIP041AN', name: 'CHICKEN SALSA MIX' },
  { code: 'WIP383AN', name: 'CORONATION CHICKEN & SULTANA MIX' },
  { code: 'WIP445AN', name: 'MISO AND YUZU MAYONNAISE MIX' },
  { code: 'WIP446AN', name: 'SANDO SLAW' },
  { code: 'WIP305AN', name: 'BRITISH CAESAR CHICKEN MIX' },
  { code: 'WIP464AN', name: 'GF CHEESE SLOW ROASTED TOMATO V2' },
  { code: 'WIP448AN', name: 'GF CHICKEN MAYO BLACK PEPPER MIX' },
  { code: 'WIP339AN', name: 'CHICKEN AND BACON MIX' },
  { code: 'WIP455AN', name: 'DIJON MUSTARD HARD CHEESE MIX' },
  { code: 'WIP226AN', name: 'NOVATION CN' },
  { code: 'WIP355AN', name: 'MEDITTERANEAN VEGETABLES CN' },
  { code: 'WIP353AN', name: 'CHEESE SAUCE MIX TOP & BASE CN' },
  { code: 'MEA063', name: 'PULLED HAM HOCK CN' },
  { code: 'MIX042', name: 'SCRAMBLED EGG CN' },
  { code: 'WIP199AN', name: 'SEASONED WHITE SAUCE CN' },
  { code: 'WIP201AN', name: 'CROQUE TOP MIX CN' },
  { code: 'WIP203AN', name: 'CHEESE & TOMATO MIX CN' },
  { code: 'WIP202AN', name: 'CROQUE TOP MIX CN' },
  { code: 'WIP195AN', name: 'MUSHROOM & EMENTEL MIX CN' },
  { code: 'WIP194AN', name: 'CROQUE TOP MIX CN' },
  { code: 'WIP200AN', name: 'GRATED MOZZARELLA & CHEDDAR CN' },
  { code: 'WIP204AN', name: 'TUNA MELT MIX CN' },
  { code: 'MIX043', name: 'CHESSE & PESTO MIX CN' },
  { code: 'MIX045', name: 'CHICKEN & PESTO MIX CN' },
  { code: 'WIP215AN', name: 'CHEESE & SEASONED WHITE SAUCE MIX CN' },
  { code: 'WIP219AN', name: 'TOMATO PASTA CN' },
  { code: 'WIP240AN', name: 'VEGAN MOZZARELLA, TOMATO & RED PEPPER MIX CN' },
  { code: 'WIP251AN', name: 'BLACK PEPPER MAYO MIX BASE CN' },
  { code: 'WIP272AN', name: 'TUNA HORSERADISH MIX CN' },
  { code: 'WIP274AN', name: 'HONEY & MUSTRAD DRESSING CN' },
  { code: 'WIP265AN', name: 'GRAIN & CHICKPEA MIX CN' },
  { code: 'WIP263AN', name: 'CUCUMBER & MINT MAYO MIX CN' },
  { code: 'WIP319AN', name: 'BBQ PULLED PORK MIX CN' },
  { code: 'WIP318AN', name: 'WINTER SLAW MIX CN' },
  { code: 'WIP370AN', name: 'TARTAR SAUCE CN' },
  { code: 'WIP375AN', name: 'GRAIN MIX CN' },
  { code: 'WIP424AN', name: 'BRITISH CORONATION CHICKEN MIX' },
  { code: 'WIP425AN', name: 'EGG MAYONNAISE MIX' },
  { code: 'WIP426AN', name: 'RED PESTO MAYONNAISE' },
  { code: 'WIP393AN', name: 'CHICKEN & PESTO MIX H SMITH' },
  { code: 'WIP063AN', name: 'ROAST TOMATO HOUMOUS' },
  { code: 'WIP374AN', name: 'LEMON HARISSA DRESSING' },
  { code: 'WIP390AN', name: 'HELLMANN EGG MAYO' },
  { code: 'WIP321AN', name: 'PESTO TOMATO MIX CDM' },
  { code: 'WIP385AN', name: 'AVACADO & JALAPENO TUNA MAYO MIX -- CDM' },
  { code: 'WIP386AN', name: 'PICKLED CUCUMBER MIX -- CDM' },
  { code: 'WIP322AN', name: 'CDM CHICKEN CEASER MIX -- CDM' },
  { code: 'WIP323AN', name: 'ROSE HARRISSA RANCH STYLE MIX -- CDM' },
  { code: 'WIP384AN', name: 'HOT HONEY JALAPENO MAYO MIX -- CDM' },
  { code: 'WIP388AN', name: 'BASIL PASTA -- CDM' },
  { code: 'WIP389AN', name: 'PESTO YOGURT CHICKEN -- CDM' },
  { code: 'WIP390AN', name: 'TOMATO HOT HONEY HARRISSA PASTA -- CDM' },
  { code: 'WIP440AN', name: 'NADUJA LEMON MAYO' },
  { code: 'WIP330AN', name: 'SEASONED MOZZARELLA' },
  { code: 'WIP453AN', name: 'PANCETTA & STUFFING MAYO' },
  { code: 'WIP454AN', name: 'CABAGE AND CRANBERRY SLAW' },
  { code: 'WIP363AN', name: 'SCRAMBLED EGG MIX AVANTI' },
  { code: 'MIX050', name: 'LEMON PEPPER MAYONNAISE AVANTI' },
  { code: 'WIP422AN', name: 'TABBOULEH PARSLEY SALAD AND VEGAN YOGHURT MIX AVANTI' },
  { code: 'WIP423AN', name: 'VEGAN TARRAGON MAYONNAISE MIX AVANTI' },
  { code: 'MIX051', name: 'LEMON AND BLACK PEPPER CRÈME FRAICHE MAYO MIX AVANTI' },
  { code: 'WIP373AN', name: 'PICKLED RADISH STICKS (DRAINED) AVANTI' },
  { code: 'WIP027AN', name: 'EGG MAYONNAISE MIX AVANTI AND TWELVE' },
  { code: 'WIP365AN', name: 'SLOW ROASTED TOMATO MIX AVANTI' },
  { code: 'WIP067AN', name: 'CHICKEN CAESAR MIX AVANTI' },
  { code: 'WIP451AN', name: 'PICKLED RED ONION (TO BE DRAINED)' },
  { code: 'WIP450AN', name: 'VEGAN APPLE OATS MIX' },
  { code: 'WIP449AN', name: 'BIRRIA RICE MIX' },
  { code: 'WIP281AN', name: 'BLACK BEAN AVOCADO SWEETCORN MIX' },
  { code: 'WIP282AN', name: 'CHIPOTLE LIME MAYO MIX' },
  { code: 'WIP285AN', name: 'RED ONION LIME MIX' },
  { code: 'WIP298AN', name: 'VEGAN CORONATION GREEN CHICKPEA MIX' },
  { code: 'WIP455AN', name: 'DIJON MUSTARD & HARD CHEESE' },
  { code: 'WIP441AN', name: 'SRIRACHA PULLED PORK' },
  { code: 'WIP442AN', name: 'ASIAN SLAW WITH MAYO' },
  { code: 'WIP443AN', name: 'KEWPIE EGG MAYO MIX' },
  { code: 'WIP444AN', name: 'CHIVE MAYO MIX' },
  { code: 'WIP445AN', name: 'MISO AND YUZU MAYONNAISE' },
  { code: 'WIP446AN', name: 'SANDO SLAW' },
  { code: 'WIP048AN', name: 'PULLED CHICKEN MAYONNAISE' },
  { code: 'WIP472AN', name: 'KATSU POTATO MAYONNAISE' },
  { code: 'WIP473AN', name: 'KATSU CABBAGE SLAW' },
  { code: 'WIP474AN', name: 'GREEN CURRY MAYONNAISE' },
  { code: 'WIP475AN', name: 'THAI CHICKEN MAYO MIX' },
  { code: 'WIP476AN', name: 'SRIRACHA MAYONNAISE' },
];